### ISSUE TITLE
running drools on wildfly

### ISSUE THREAD

**Issue by aurelianu** [ezequielgrande/droolsjbpm-quickstart-guide#1]
Hello there,

I have tried your drools example "http://www.plugtree.com/drools-basic-rules-example/" and all works fine from Junit context, but not on wildfly... I have no ideea why, no rules are fired in wildfly context. Can you please help me? 

http://stackoverflow.com/questions/27920130/drools-in-junit-context-and-wildfly-context

Thank you and 
Best regards!

**Comment by ezequielgrande** [comment]
Hi!
I have never used Wildfly with Drools, but I guess that the first thing
that you can try is to have a rule with an empty condition and a
consequence that you can track. I have read your question in StackOverflow
and it seems that the .drl is processed correctly.

You can have a rule of this type:

rule "Debug rule"
when
  // Empty
then
   System.out.println("----executed");
   // also you could try to log a message, by using a global variable that
references your Logger.
end

This rule will be triggered once, when the fireAllRules is called. By doing
this, you can assert if the rules are actually fired or not.

Also, you could take a look to these listeners that Drools provides:
- org.drools.core.event.DebugAgendaEventListener
- org.drools.core.event.DebugRuleRuntimeEventListener

They can be added to the session with session.addEventListener(theListener).

I hope that this helps to debug your code :)

Good luck!
